### ISSUE TITLE
doi check fails for 0000-0098 (0)

### ISSUE THREAD

**Issue by stefanjakobsson** [datacite/cirneco#2]
If the base32-DOI is generated from 0, the resulting string is 0000-0098, but this does not validate with "doi check" since it checks that the decoded value is *larger* than zero.

See https://github.com/datacite/cirneco/blob/eb656c368b856a6bb130c4b9b289438a8b690559/lib/cirneco/doi.rb#L84

**Comment by kjgarza** [comment]
### Expected Behaviour


cirneco should accept 0000-0098 as doi name

### Current Behaviour


cirneco fails to accept {prefix}/0000-0098 as doi name

### Steps to Reproduce



```
    it 'checks a doi invalid checksum' do
      doi = "5072/0000-0098"
      expect { subject.check doi }.to output("Checksum for #{doi} is valid\n").to_stdout
    end

```



### Context (Environment)






### Hypothesis


the fail response for decode a doi should not be 0 but nil.

### Detailed Description



to change the response or check of decode fail

https://github.com/datacite/base32-url/blob/ff013f43fa1e889d55d679e7a8d4fc43592e1f16/lib/base32/url.rb#L113


### Possible Implementation


- [x] to change the response or check of decode fail

**Comment by kjgarza** [comment]
fix in https://github.com/datacite/cirneco/commit/46a57beaa9fead5984ced35dedc40ed924e753f8
