### ISSUE TITLE
enable bulk DOI transfer via file

### ISSUE THREAD

**Issue by daslerr** [datacite/cirneco#3]
To assist with an upcoming client DOI transfer, tweak cirneco to enable bulk DOI transfer via file. The file will have one DOI per line (and nothing else), and the filename will contain the client ID that the DOIs should be transferred into.

**Comment by kjgarza** [comment]
this is the previous features it seems :

https://github.com/datacite/cirneco/commit/14ef544d32742b5f9cad7a0747f550700f5fd7e9

**Comment by kjgarza** [comment]
Can the new MDS `poodle` make DOI Transfers ??? I don't think it can.
https://github.com/datacite/poodle/blob/437983a0bf5881b54582cd3d595b485e8943c253/app/controllers/metadata_controller.rb#L37

Then I think cirneco by itself, cannot make a DOI Transfer because it's a client of poodle not lupo. Lupo can make transfers.

Maybe we could add a type in `poodle` for when transfers happen.  But I will need to check other hiccups . (eg. metadata validation etc) https://github.com/datacite/poodle/blob/437983a0bf5881b54582cd3d595b485e8943c253/app/controllers/concerns/metadatable.rb#L18

**Comment by kjgarza** [comment]
Another Alternative is to include `Lupo` endpoints for `cirneco`

**Comment by kjgarza** [comment]
https://github.com/datacite/cirneco/pull/4
